/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error-container": "#93000a",
        "surface-container-low": "#171c20",
        "surface-container": "#1b2024",
        "primary-fixed-dim": "#7bd0ff",
        "secondary-container": "#39485a",
        "surface": "#0f1418",
        "surface-variant": "#303539",
        "secondary": "#b9c8de",
        "on-background": "#dee3e8",
        "surface-bright": "#343a3e",
        "on-primary": "#00354a",
        "tertiary-container": "#f1a02b",
        "on-surface": "#dee3e8",
        "surface-container-high": "#252b2e",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#39485a",
        "tertiary": "#ffc176",
        "outline": "#87929a",
        "on-tertiary": "#472a00",
        "secondary-fixed-dim": "#b9c8de",
        "secondary-fixed": "#d4e4fa",
        "inverse-primary": "#00668a",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#a7b6cc",
        "on-surface-variant": "#bdc8d1",
        "tertiary-fixed-dim": "#ffb960",
        "on-tertiary-fixed": "#2a1700",
        "inverse-on-surface": "#2c3135",
        "surface-container-lowest": "#0a0f12",
        "surface-dim": "#0f1418",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-container": "#004965",
        "surface-container-highest": "#303539",
        "primary-fixed": "#c4e7ff",
        "on-secondary": "#233143",
        "on-primary-fixed": "#001e2c",
        "tertiary-fixed": "#ffddb8",
        "surface-tint": "#7bd0ff",
        "primary-container": "#38bdf8",
        "primary": "#8ed5ff",
        "background": "#0f1418",
        "on-secondary-fixed": "#0d1c2d",
        "outline-variant": "#3e484f",
        "inverse-surface": "#dee3e8",
        "on-primary-fixed-variant": "#004c69",
        "on-tertiary-container": "#613b00"
      },
      "borderRadius": {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "0.5rem",
        "row-height-condensed": "28px",
        "row-height-standard": "36px",
        "container-padding": "1rem",
        "unit": "4px",
        "margin": "24px",
        "md": "16px",
        "sm": "8px",
        "lg": "24px",
        "xl": "40px"
      },
      "fontFamily": {
        "label-caps": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "label-caps": ["11px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "h2": ["18px", {"lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h1": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "mono-data": ["12px", {"lineHeight": "16px", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
