/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error-container": "var(--error-container)",
        "surface-container-low": "var(--surface-container-low)",
        "surface-container": "var(--surface-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "secondary-container": "var(--secondary-container)",
        "surface": "var(--surface)",
        "surface-variant": "var(--surface-variant)",
        "secondary": "var(--secondary)",
        "on-background": "var(--on-background)",
        "surface-bright": "var(--surface-bright)",
        "on-primary": "var(--on-primary)",
        "tertiary-container": "var(--tertiary-container)",
        "on-surface": "var(--on-surface)",
        "surface-container-high": "var(--surface-container-high)",
        "on-error": "var(--on-error)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "tertiary": "var(--tertiary)",
        "outline": "var(--outline)",
        "on-tertiary": "var(--on-tertiary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "secondary-fixed": "var(--secondary-fixed)",
        "inverse-primary": "var(--inverse-primary)",
        "error": "var(--error)",
        "on-error-container": "var(--on-error-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        "on-surface-variant": "var(--on-surface-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "surface-dim": "var(--surface-dim)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-primary-container": "var(--on-primary-container)",
        "surface-container-highest": "var(--surface-container-highest)",
        "primary-fixed": "var(--primary-fixed)",
        "on-secondary": "var(--on-secondary)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "surface-tint": "var(--surface-tint)",
        "primary-container": "var(--primary-container)",
        "primary": "var(--primary)",
        "background": "var(--background)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "inverse-surface": "var(--inverse-surface)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-tertiary-container": "var(--on-tertiary-container)"
      },
      "borderRadius": {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "0.5rem",
        "row-height-condensed": "28px",
        "row-height-standard": "36px",
        "container-padding": "1rem",
        "unit": "4px",
        "margin": "24px",
        "md": "16px",
        "sm": "8px",
        "lg": "24px",
        "xl": "40px"
      },
      "fontFamily": {
        "label-caps": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"]
      },
      "fontSize": {
        "label-caps": ["clamp(9px, 2.5vw, 11px)", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "h2": ["clamp(14px, 4vw, 18px)", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h1": ["clamp(18px, 5vw, 24px)", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body": ["clamp(11px, 3vw, 13px)", {"lineHeight": "1.5", "fontWeight": "400"}],
        "mono-data": ["clamp(10px, 2.8vw, 12px)", {"lineHeight": "1.4", "fontWeight": "500"}],
        "xs": ["clamp(10px, 2.5vw, 12px)", {"lineHeight": "1.3"}],
        "sm": ["clamp(12px, 3vw, 14px)", {"lineHeight": "1.4"}],
        "base": ["clamp(14px, 3.5vw, 16px)", {"lineHeight": "1.5"}],
        "lg": ["clamp(16px, 4vw, 18px)", {"lineHeight": "1.4"}],
        "xl": ["clamp(18px, 4.5vw, 20px)", {"lineHeight": "1.3"}],
        "2xl": ["clamp(20px, 5vw, 24px)", {"lineHeight": "1.2"}],
        "3xl": ["clamp(24px, 6vw, 30px)", {"lineHeight": "1.2"}],
        "fluid-7": ["clamp(6px, 1.5vw, 7px)", {"lineHeight": "1"}],
        "fluid-8": ["clamp(7px, 1.8vw, 8px)", {"lineHeight": "1"}],
        "fluid-9": ["clamp(8px, 2vw, 9px)", {"lineHeight": "1.2"}],
        "fluid-10": ["clamp(9px, 2.2vw, 10px)", {"lineHeight": "1.4"}],
        "fluid-11": ["clamp(10px, 2.5vw, 11px)", {"lineHeight": "1.4"}],
        "fluid-12": ["clamp(10px, 2.8vw, 12px)", {"lineHeight": "1.4"}],
        "fluid-14": ["clamp(12px, 3.2vw, 14px)", {"lineHeight": "1.5"}],
        "fluid-16": ["clamp(14px, 3.8vw, 16px)", {"lineHeight": "1.5"}],
        "fluid-18": ["clamp(16px, 4vw, 18px)", {"lineHeight": "1.4"}],
        "fluid-20": ["clamp(18px, 4.5vw, 20px)", {"lineHeight": "1.3"}],
        "fluid-24": ["clamp(22px, 5vw, 24px)", {"lineHeight": "1.2"}]
      }
    },
  },
  plugins: [],
}
